# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-06-06 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_urls_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='clicked',
            field=models.BigIntegerField(default=0),
        ),
    ]
